sudo: required
services:
  - docker

before_install:
  - docker build -t bkituyi/docker-react -f Dockerfile.dev .

script:
  - docker run bkituyi/docker-react npm run test -- --coverage

deploy:
  provider: gae
  keyfile: client-secret.json
  project: docker-react